# Generated by Django 2.1.5 on 2022-07-22 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_auto_20220722_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='conten',
            new_name='content',
        ),
    ]
